matrix:
- name: Python Source
  sources:
  - 'src/**/*.py'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.python:
      comments: true
      docstrings: true
      strings: true
