apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spark-service-template
  namespace: spark
spec:
  refreshInterval: 8760h
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore
  target:
    name: spark-service-template
    creationPolicy: Owner
  data:
    - secretKey: ""
      remoteRef:
        key: ""